angular_rails/config/routes.rb
AngularRails::Application.routes.draw do
  get "static/index"

  root to: 'static#index'
  resources :stalls

end

angular_rails/app/models/stall.rb
class Stall < ActiveRecord::Base
  attr_accessible :description, :name, :price
end

angular_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

angular_rails/app/controllers/stalls_controller.rb
class StallsController < ApplicationController
  # GET /stalls
  # GET /stalls.json
  def index
    @stalls = Stall.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stalls }
    end
  end

  # GET /stalls/1
  # GET /stalls/1.json
  def show
    @stall = Stall.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stall }
    end
  end

  # GET /stalls/new
  # GET /stalls/new.json
  def new
    @stall = Stall.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stall }
    end
  end

  # GET /stalls/1/edit
  def edit
    @stall = Stall.find(params[:id])
  end

  # POST /stalls
  # POST /stalls.json
  def create
    @stall = Stall.new(params[:stall])

    respond_to do |format|
      if @stall.save
        format.html { redirect_to @stall, notice: 'Stall was successfully created.' }
        format.json { render json: @stall, status: :created, location: @stall }
      else
        format.html { render action: "new" }
        format.json { render json: @stall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stalls/1
  # PUT /stalls/1.json
  def update
    @stall = Stall.find(params[:id])

    respond_to do |format|
      if @stall.update_attributes(params[:stall])
        format.html { redirect_to @stall, notice: 'Stall was successfully updated.' }
        format.json { render json: @stall }
      else
        format.html { render action: "edit" }
        format.json { render json: @stall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stalls/1
  # DELETE /stalls/1.json
  def destroy
    @stall = Stall.find(params[:id])
    @stall.destroy

    respond_to do |format|
      format.html { redirect_to stalls_url }
      format.json { head :no_content }
    end
  end
end

angular_rails/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

angular_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

angular_rails/app/helpers/stalls_helper.rb
module StallsHelper
end

angular_rails/app/helpers/static_helper.rb
module StaticHelper
end

angular_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='leatherLaneMarketApp'>
<head>
  <title>AngularRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

angular_rails/app/views/stalls/_form.html.erb
<%= form_for(@stall) do |f| %>
  <% if @stall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stall.errors.count, "error") %> prohibited this stall from being saved:</h2>

      <ul>
      <% @stall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

angular_rails/app/views/stalls/edit.html.erb
<h1>Editing stall</h1>

<%= render 'form' %>

<%= link_to 'Show', @stall %> |
<%= link_to 'Back', stalls_path %>

angular_rails/app/views/stalls/index.html.erb
<h1>Listing stalls</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stalls.each do |stall| %>
  <tr>
    <td><%= stall.name %></td>
    <td><%= stall.description %></td>
    <td><%= stall.price %></td>
    <td><%= link_to 'Show', stall %></td>
    <td><%= link_to 'Edit', edit_stall_path(stall) %></td>
    <td><%= link_to 'Destroy', stall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stall', new_stall_path %>

angular_rails/app/views/stalls/new.html.erb
<h1>New stall</h1>

<%= render 'form' %>

<%= link_to 'Back', stalls_path %>

angular_rails/app/views/stalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stall.name %>
</p>

<p>
  <b>Description:</b>
  <%= @stall.description %>
</p>

<p>
  <b>Price:</b>
  <%= @stall.price %>
</p>


<%= link_to 'Edit', edit_stall_path(@stall) %> |
<%= link_to 'Back', stalls_path %>